<a href="https://colab.research.google.com/github/asmipandey18/Machine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy(Numerical python)
- python library used to working with array.
- It also uses linear algebra, fourier tarnsform and matrices operations.
- why is it differ than list?

   - its because its speed, numpy arrays are stored at one contineous place in memory, so process can be very efficient and fast

In [ ]:
!pip install numpy
## for VS code

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


## Creating an arrays using numPy.

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


Create a NumPy ndarray Object

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
## 0-D Arrays
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
## 1-D array
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
## 2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
## 3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,5],[5,6,9]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 5]
  [5 6 9]]]


Check Number of Dimensions in an Numpy Array?

In [ ]:
## Check Number of dimension in an NumPy Array?
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3,])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1,2,3], [2,3,4]], [[3,5,6,], [6,5,8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
# create an array of 5 dimension and verify its dimension.

import numpy as np

arr = np.array([1,2,3,4], ndmin=10)

print(arr)
print('number of dimensions :', arr.ndim)




[[[[[[[[[[1 2 3 4]]]]]]]]]]
number of dimensions : 10


## Access Array Element

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr[2])

3


In [ ]:
# 3rd and 4th element add

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


Accessing 2-D array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print('2nd element on 1st row: ', arr[0, 1])

In [ ]:
print('second last element on 2nd row', arr[1, 3])

second last element on 2nd row 9


## Indexing
Indexing means accessing a specific element from an array.

In [1]:
## 1D array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [3]:
## 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0, 1])
# print(arr[1, 2])

20


## Slicing
Slicing means extracting a portion of an array.

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


In [5]:
## 2D slicing
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


## Data type
NumPy arrays have a data type (dtype).

common datatpes like
int,
float,
bool,
str

In [23]:
arr = np.array([10, 20, 30])

print(arr)
print(arr.dtype)

[10 20 30]
int64


In [9]:
arr = np.array([10, 20, 30], dtype=str)

print(arr)
print(arr.dtype)

['10' '20' '30']
<U2


In [24]:
arr = np.array([10, 20, 30], dtype=float)

print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


## Array shape and Reshape
# shape
shape tells us the dimensions of an array.

In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)


 Reshape
reshape() changes the shape without changing the number of elements.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## Sorting
NumPy provides np.sort() to sort an array.

In [12]:
arr = np.array([50, 10, 40, 20, 30])

print(np.sort(arr))

[10 20 30 40 50]


In [13]:
# 2D array
arr = np.array([
    [30, 10, 20],
    [60, 40, 50]
])

print(np.sort(arr))

[[10 20 30]
 [40 50 60]]


## Array Search
NumPy provides np.where() to find the positions/indices where a condition is true.

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(np.where(arr > 25))

(array([2, 3, 4]),)


In [15]:
## to search for specific value
print(np.where(arr == 30))

(array([2]),)


## Apply Filters
NumPy supports Boolean filtering.

In [16]:
arr = np.array([10, 20, 30, 40, 50])

filtered = arr[arr > 25]

print(filtered)

[30 40 50]


In [17]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[(arr > 20) & (arr < 50)])

[30 40]


## Random Number Generation
NumPy has a random module for generating random numbers.


In [18]:
random_number = np.random.randint(1, 10)

print(random_number)

2


In [19]:
## multiple random integer
numbers = np.random.randint(1, 100, 5)

print(numbers)

[36 50  9 18  6]


In [20]:
## random 2D array
arr = np.random.randint(1, 10, size=(3, 3))

print(arr)

[[3 2 8]
 [9 6 6]
 [5 7 4]]


## Array Joining
Joining means combining two or more arrays.

syntax:
np.concatenate()

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

print(result)

[1 2 3 4 5 6]


In [22]:
## joining 2D array
arr1 = np.array([
    [1, 2],
    [3, 4]
])

arr2 = np.array([
    [5, 6],
    [7, 8]
])

result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
