<a href="https://colab.research.google.com/github/asmipandey18/Machine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy(Numerical python)
- python library used to working with array.
- It also uses linear algebra, fourier tarnsform and matrices operations.
- why is it differ than list?

   - its because its speed, numpy arrays are stored at one contineous place in memory, so process can be very efficient and fast

In [ ]:
!pip install numpy
## for VS code

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


## Creating an arrays using numPy.

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


Create a NumPy ndarray Object

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
## 0-D Arrays
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
## 1-D array
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
## 2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
## 3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,5],[5,6,9]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 5]
  [5 6 9]]]


Check Number of Dimensions in an Numpy Array?

In [ ]:
## Check Number of dimension in an NumPy Array?
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3,])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1,2,3], [2,3,4]], [[3,5,6,], [6,5,8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
# create an array of 5 dimension and verify its dimension.

import numpy as np

arr = np.array([1,2,3,4], ndmin=10)

print(arr)
print('number of dimensions :', arr.ndim)




[[[[[[[[[[1 2 3 4]]]]]]]]]]
number of dimensions : 10


## Access Array Element

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr[2])

3


In [ ]:
# 3rd and 4th element add

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


Accessing 2-D array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print('2nd element on 1st row: ', arr[0, 1])

In [ ]:
print('second last element on 2nd row', arr[1, 3])

second last element on 2nd row 9
